### ISSUE TITLE
State of checkable item don't get saved. Get reset on scrolling the list

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-CustomChoiceList#2]
JUST SHOW ME ISSUE : https://drive.google.com/file/d/0B51Rme2UnY78dUlFSXFLeEd0OGc/view?usp=sharing

I have edited a very small part of your code.
What I want to achieve is that whenever any list item is visible on the screen it should get toggle.
So, I have added a handler in class 'CheckableLinearLayout' as 

public class CheckableLinearLayout extends LinearLayout implements Checkable {
    private static final int[] CHECKED_STATE_SET = {android.R.attr.state_checked};

```
private static final String TAG = "CheckableLinearLayout";

private boolean mChecked = false;
private Handler mHandler = null;
private int position = -1;

public CheckableLinearLayout(Context context, AttributeSet attrs) {
    super(context, attrs);
}

public boolean isChecked() {
    return mChecked;
}

public void setChecked(boolean b) {
    if (b != mChecked) {
        mChecked = b;
        refreshDrawableState();
    }
}

public void toggle() {
    setChecked(!mChecked);
}

public void setAutoToggle(int position) {
    this.position = position;
    mHandler = new Handler();
    mHandler.postDelayed(new AutoCheck(), 1000);
}

public int getPosition() {
    return position;
}

@Override
public int[] onCreateDrawableState(int extraSpace) {
    Log.d(TAG, "onCreate :" + position + "Checked :" + isChecked());
    final int[] drawableState = super.onCreateDrawableState(extraSpace + 1);
    if (isChecked()) {
        mergeDrawableStates(drawableState, CHECKED_STATE_SET);
    }
    return drawableState;
}

class AutoCheck implements Runnable {
    @Override
    public void run() {
        Log.d(TAG, "Toggling : " + position + " (" + isChecked() + " -> " + !isChecked() + ")");
        toggle();
    }
}
```

}

And also I have started toggle thread for each visible view using getView() method.
Adapter is as follows

private class MyAdapter extends BaseAdapter {

```
    private static final String TAG = "Adapter";

    @Override
    public int getCount() {
        return Cheeses.CHEESES.length;
    }

    @Override
    public String getItem(int position) {
        return Cheeses.CHEESES[position];
    }

    @Override
    public long getItemId(int position) {
        return Cheeses.CHEESES[position].hashCode();
    }

    @Override
    public View getView(int position, View convertView, ViewGroup container) {
        if (convertView == null) {
            convertView = getLayoutInflater().inflate(R.layout.list_item, container, false);


            ((TextView) convertView.findViewById(android.R.id.text1))
                    .setText(getItem(position));
        }

        Log.d(TAG, "Getting View : " + position);

        ((CheckableLinearLayout) convertView).setAutoToggle(position);
        return convertView;
    }
}
```

AND I HAVE CHANGED NOTHING...

WHAT MY PROBLEM IS...

It work as expected. When I scroll the list getView() method is called for new views and that item got toggle ... Horrah !

BUT the item that gone out of the screen gets reset to uncheck. And when I scroll up again getView() is called and item gets checked again instead of uncheck.

Also when I click on any item other item gets affected.

Here is the link to show you the issue

https://drive.google.com/file/d/0B51Rme2UnY78dUlFSXFLeEd0OGc/view?usp=sharing

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositori
