### ISSUE TITLE
Screenshots are still missing, more than a year since the first report

### ISSUE THREAD

**Issue by or-else** [googlesamples/android-CustomChoiceList#3]
Does anyone actually monitor these reports?

**Comment by albert0m** [comment]
https://github.com/googlesamples/android-CustomChoiceList/blob/master/screenshots/main.png

this is the only screenshot you need

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositori
