### ISSUE TITLE
save-the-state-of-the-check-box-items-in-a-single-choice-list-view

### ISSUE THREAD

**Issue by harshipatelb** [googlesamples/android-CustomChoiceList#4]
>  @NonNull
>     @Override
>     public View getView(final int position, View convertView, ViewGroup parent) {
>         if (convertView == null) {
>             holder = new ViewHolder();
>             convertView = inflater.inflate(R.layout.raw_sort_result, null);
>             holder.tv_aggregrator_product = (TextView) convertView.findViewById(R.id.tv_raw_sort_result);
>             holder.chk_sort_result = (CheckBox) convertView.findViewById(R.id.chk_sort_result);
>             convertView.setTag(holder);
>         } else {
>             holder = (ViewHolder) convertView.getTag();
>         } 
>         preferences = ctx.getSharedPreferences("mypref", Context.MODE_PRIVATE);
>         editor = preferences.edit();
>         holder.chk_sort_result.setTag(position);
>         if (position == selectedPosition) {
>             holder.chk_sort_result.setChecked(true);
>         } else {
>             holder.chk_sort_result.setChecked(false);
>         }
> 
>         holder.chk_sort_result.setOnClickListener(onStateChangedListener(holder.chk_sort_result, position));
>         return convertView;
>     }
>     private View.OnClickListener onStateChangedListener(final CheckBox chk_sort_result, final int position) {
>         return new View.OnClickListener() {
>             @Override
>             public void onClick(View v) {
>                 if (chk_sort_result.isChecked()) {
>                     selectedPosition = position;
>                     name = list.get(position).getTv_aggregrator_product();
>                     editor.putBoolean("savecheckbox", true);
>                     editor.putString("Selected_Name", name);
>                     editor.commit();
>                 } else {
>                     selectedPosition = -1;
>                     editor.clear();
>                     editor.commit();
>                 }
>                 notifyDataSetChanged();
>             }
>         };
>     }
> }
>

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositori
