### ISSUE TITLE
Screenshot links giving 404

### ISSUE THREAD

**Issue by petera703** [googlesamples/android-CustomChoiceList#6]
Both the screenshot links at https://github.com/googlesamples/android-CustomChoiceList/#readme give a 404 error

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositori
